### ISSUE TITLE
[First week] Create a version of the app which uses the old static hooks

### ISSUE THREAD

**Issue by imjalpreet** [interfasys/mediametadata#13]
The related commit: [f86c961](https://github.com/interfasys/mediametadata/commit/f86c961c951ad13a376f30e40a5ca30246caaa4b)

**Comment by oparoz** [comment]
I think you've linked the wrong commit. That commit is about trying to catche the events using the old hooks and is part of #15

**Comment by imjalpreet** [comment]
@oparoz Doesn't the old hooks method use the static hooks? I thought that way, and that's why I linked this commit. Also, I created #15 for the task of triggering the hooks for the sync client. Correct me if I have done some mistake.

**Comment by oparoz** [comment]
The old hooks methods use static hooks, yes, but this work all happened when we were trying to understand why the hooks didn't work via DAV events. I suggested you update your 2nd app which used those old hooks to see if it was a problem with the new hooks only.
Does that sound correct?

**Comment by imjalpreet** [comment]
@oparoz, Yeah that's correct. But I think this commit doesn't include those changes, this commit just includes the basic skeleton of the old hooks. The DAV changes are included in this commit: [7f48f2c](https://github.com/interfasys/mediametadata/commit/7f48f2c94c80594f9b1abd87a36b998cf6c000b2)

Am I right?

**Comment by oparoz** [comment]
OK, I've reviewed the emails and the code. I had asked you to update the version of your trialApp so that we could test using both the old and the new hooks because the DAV changes from my PR were not triggering the expected events.

So yes, this is a separate sub-task of #15
