### ISSUE TITLE
[First week] Load the App onto DAV access

### ISSUE THREAD

**Issue by imjalpreet** [interfasys/mediametadata#15]
The related commit: [7f48f2c](https://github.com/interfasys/mediametadata/commit/7f48f2c94c80594f9b1abd87a36b998cf6c000b2)

This also solved the issue of triggering the hooks when the image is uploaded using sync client.

**Comment by oparoz** [comment]
Please assign yourself and add the milestone and a label for each of your tasks, both here and in the PMS

**Comment by oparoz** [comment]
The 1,2,3,4 labels are for PRs, to indicate the state they're in.
For issues, you can use things like "In progress", when you're working on something and "QA" when the PR is being reviewed. There is no "To release" state for issues. They auto-close once the PR is merged, if you've added the issue number in there.
