### ISSUE TITLE
Install Codeception unit testing

### ISSUE THREAD

**Issue by oparoz** [interfasys/mediametadata#3]
For the Metadata extraction phase we only need unit testing.

Some documentation on how it should work:
https://github.com/owncloud/gallery/blob/master/tests/README.MD

**Comment by imjalpreet** [comment]
@oparoz I have installed codeception and it's working.
![codeception](https://cloud.githubusercontent.com/assets/6432146/15886194/2a5819ee-2d79-11e6-85e1-0f5f6caf3076.png)

**Comment by oparoz** [comment]
Yes, but this ticket is about configuring it so that it can run your unit tests.

**Comment by imjalpreet** [comment]
@oparoz Sorry, I misunderstood it. Also, I wanted to ask a general question. Is it necessary to generate a test using the command mentioned in the README (php vendor/bin/codecept g:phpunit unit service/MyServiceTest)? Does this command do something more than just creating the required files? Will it not work if I create a file on my own and write the tests in it?

**Comment by oparoz** [comment]
No problem.

> Is it necessary to generate a test using the command mentioned in the README

Not at all, it's simply an easy way to create them. You can also alter the template so that it generates exactly what you want.

> Will it not work if I create a file on my own and write the tests in it?

It will. It's really up to you.

All the documentation is here:
http://codeception.com/docs/05-UnitTests
