### ISSUE TITLE
Set up Travis-CI

### ISSUE THREAD

**Issue by oparoz** [interfasys/mediametadata#4]
We need automatic testing of all PRs

Can be based off the config for Gallery:
https://github.com/owncloud/gallery/blob/master/.travis.yml

**Comment by oparoz** [comment]
I've turned on Travis and Scrutinizer analysers, so PRs and merges are now automatically checked.

**Comment by imjalpreet** [comment]
@oparoz Could you also check the .travis.yml file and suggest what else should be changed?

**Comment by oparoz** [comment]
OK, I just did and I think it's working as expected (difficult to say without tests).

Do you have any other questions regarding the content of that file?

**Comment by imjalpreet** [comment]
@oparoz No, not as of now. I will ask you if I have in the future. Also, I will add the test as soon as possible.
